# Format: {A}_{S}
# A = algorithm name, lowercase, without space (must match the src/*.c and src/*.h name)
# S = waiting strategy. original = hardcoded in the algorithm (see README), otherwise spinlock/spin_then_park/park

ALGORITHMS= \
alockepfl_original           \
hmcs_original                \
cbomcs_spinlock 			 \
backoff_original             \
mcs_spinlock \
mcs_spin_then_park           \
spinlock_original            \
malthusian_spinlock          \
malthusian_spin_then_park    \
ttas_original                \
ticket_original              \
clh_spinlock                 \
clh_spin_then_park           \
pthreadinterpose_original    \
htlockepfl_original          \
hyshmcs_original			 \
cbomcs_spin_then_park 		 \
cptltkt_original 			 \
ctkttkt_original 			 \
partitioned_original         \
concurrency_original	     \

# mcsepfl_original             \
# spinlockepfl_original        \
# ttasepfl_original            \
# ticketepfl_original          \
# clhepfl_original             \
# pthreadadaptive_original     \
# mcstp_original               \
# empty_original               \
