# Format: {A}_{S}
# A = algorithm name, lowercase, without space (must match the src/*.c and src/*.h name)
# S = waiting strategy. original = hardcoded in the algorithm (see README), otherwise spinlock/spin_then_park/park

LOCAL=0
COMM_PROT=RDMA
DEBUG=NO
OFLAG=O2
MPI=MPI
CORRECTNESS=CORRECTNESS

ALGORITHMS= \
alockepfl_original \
# backoff_original \
# hmcs_original \
# malthusian_spinlock \
# fns_spinlock \
# pthreadinterpose_original \

# concurrency_original \
# cbomcs_spin_then_park \
# cbomcs_spinlock \
# clh_spin_then_park \
# clh_spinlock \
# cna_spinlock \
# cptltkt_original \
# ctkttkt_original \
# fnm_spin_then_park \
# htlockepfl_original \
# hyshmcs_original \
# malthusian_spin_then_park \
# mcs_spin_then_park \
# mcs_spinlock \
# mutexee_original \
# partitioned_original \
# spinlock_original \
# ticket_original \
# ttas_original \

# mcsepfl_original             \
# spinlockepfl_original        \
# ttasepfl_original            \
# ticketepfl_original          \
# clhepfl_original             \
# pthreadadaptive_original     \
# mcstp_original               \
# empty_original               \
